### ISSUE TITLE
GitHub Actions: build failure at step Install Qt on macOS

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#1279]
See for example: https://github.com/vgc/vgc/actions/runs/4874265919/jobs/8695906506

```
python3 -m aqt install 5.15.2 mac desktop -O /Users/runner/work/vgc/Qt
aqtinstall(aqt) v1.2.5 on Python 3.7.16 [CPython Clang 12.0.0 (clang-1200.0.32.29)]
Downloaded metadata is corrupted. no element found: line 111, column 348
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/aqt/archives.py", line 220, in _parse_update_xml
    self.update_xml = ElementTree.fromstring(self.update_xml_text)
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/xml/etree/ElementTree.py", line 1316, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 111, column 348

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/aqt/__main__.py", line 27, in <module>
    sys.exit(main())
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/aqt/__init__.py", line 31, in main
    return cli.run()
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/aqt/installer.py", line 675, in run
    result = args.func(args)
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/aqt/installer.py", line 259, in run_install
    timeout=timeout,
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/aqt/archives.py", line 172, in __init__
    self._get_archives()
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/aqt/archives.py", line 212, in _get_archives
    self._parse_update_xml(archive_url, target_packages)
  File "/Users/runner/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/aqt/archives.py", line 223, in _parse_update_xml
    raise ArchiveListError("Downloaded metadata is corrupted.")
aqt.exceptions.ArchiveListError: Downloaded metadata is corrupted.
Error: The process 'python3' failed with exit code 1
```

This might simply be that some servers at Qt or other mirrors are down. In the meantime, we can try to upgrade to a newer version of https://github.com/jurplel/install-qt-action (we're currently using v2, while there's a v3 out).

**Comment by dalboris** [comment]
On my local Ubuntu 22.04 machine, if I do:

```
pip3 install aqtinstall==2.1.*
python3 -m aqt list-qt mac desktop
```

It returns:

```
6.5.0
```

Looks like maybe 5.15.2 was removed?

**Comment by dalboris** [comment]
Note: official blog post from Qt where they install Qt on GitHub-hosted runner: https://www.qt.io/blog/building-qt-creator-plugins-with-github-actions

Here is their workflow file: https://github.com/cristianadam/qtcreator-doxygen/blob/master/.github/workflows/build_qmake.yml

We may want get some inspiration from there.

They directly download Qt here: 

```https://download.qt.io/online/qtsdkrepository/${url_os}/desktop/qt5_${qt_version_dotless}```

Where in our case `${url_os}` is `mac_x64` and `${qt_version_dotless}` would be `5152`.

We can check the content of the url: https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5152/

It seems to be ok at the moment.

**Comment by dalboris** [comment]
I get erratic results when checking with `aqt list-qt`, sometimes it works, sometimes it doesn't, see:

```
~$ python3 -m aqt list-qt mac desktop --arch 6.2.0
Downloaded file Updates.xml is corrupted! Detect checksum error.
Expect 92a5693c854ee01e1a10f2f1a53d1914e825c5bfb031a94958b0e2f47c56d27c: https://master.qt.io/online/qtsdkrepository/mac_x64/desktop/qt6_620/Updates.xml
Actual 9bdf1a7f84b29bab78ee360dba3e4e0443ade0de3e51c9a1b1b32552a2a2eddd: Updates.xml
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt mac desktop' to show versions of Qt available.
~$ python3 -m aqt list-qt mac desktop
6.5.0
~$ python3 -m aqt list-qt mac desktop --arch 6.2.0
clang_64
~$ python3 -m aqt list-qt mac desktop --arch 5.15.2
Downloaded file Updates.xml is corrupted! Detect checksum error.
Expect a63603bbbbdf3ca64bee7a57a5c0df1e50f97abb25d45efcecde8ce8073941c4: https://mirrors.aliyun.com/qt/online/qtsdkrepository/mac_x64/desktop/qt5_5152/Updates.xml
Actual 67aa8ee0dbd10770b42f51420f60b0bebe9dde073fe5f87eb68c0077bb92c9d4: Updates.xml
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt mac desktop' to show versions of Qt available.
~$ python3 -m aqt list-qt mac desktop --arch 5.15.2
clang_64
```

It might be a problem in the mirrors? Or a problem with https://master.qt.io that is now fixed but takes time to be propagated to the mirrors?

**Comment by dalboris** [comment]
The GitHub action works again, but the fix was simply to wait and try again later. Closing the issue, although we may want in the future to not rely on external servers for downloading and installing Qt. We may want to try the install script above ( https://github.com/cristianadam/qtcreator-doxygen/blob/master/.github/workflows/build_qmake.yml), but downloading Qt from a self-hosted reliable location, e.g., Azure.
