### ISSUE TITLE
Improve file upload in GitHub action

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#1586]
There are often errors when uploaded the GitHub actions to the server. The latests look like:

On Windows:
```
Uploading D:\a\vgc\vgc\build\deploy\Release\VGC Alpha 2023-11-28.1 Installer - No Updates.exe...Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\http\client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\http\client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\http\client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\http\client.py", line 1071, in _send_output
    self.send(chunk)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\http\client.py", line 993, in send
    self.sock.sendall(data)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\ssl.py", line 1003, in send
    return self._sslobj.write(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/a/vgc/vgc/tools/windows/deploy.py", line 1238, in <module>
    "file": file
  File "D:/a/vgc/vgc/tools/windows/deploy.py", line 1088, in post_multipart
    response = urllib.request.urlopen(request, databytes)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 1[352](https://github.com/vgc/vgc/actions/runs/7017181991/job/19089950775#step:17:353), in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
ninja: build stopped: subcommand failed.
```

On macOS:
```
Uploading commit metadata... Done.
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/http/client.py", line 1075, in _send_output
    self.send(chunk)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/http/client.py", line 997, in send
    self.sock.sendall(data)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/work/vgc/vgc/tools/macos/deploy.py", line 1199, in <module>
    "file": file
  File "/Users/runner/work/vgc/vgc/tools/macos/deploy.py", line 665, in post_multipart
    response = urllib.request.urlopen(request, databytes)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 32] Broken pipe>
make[3]: *** [CMakeFiles/deploy] Error 1
make[2]: *** [CMakeFiles/deploy.dir/all] Error 2
make[1]: *** [CMakeFiles/deploy.dir/rule] Error 2
make: *** [deploy] Error 2
Uploading /Users/runner/work/vgc/build/deploy/Release/VGC Illustration Alpha-gh1586a 2023-11-28.3.dmg...
```

I'm not sure yet whether the root cause of the problem is our server which does not handle the load (file too large, etc...), or if there's something wrong with the upload script. In any case, useful things to do could be:

1. Make the upload script more resilient by re-trying a few times if it doesn't work.
2. Separate the GitHub action into two jobs: build and deploy. This way, at least we don't have to re-build to try re-uploading the files.
3. Switch storage to Azure or other Cloud service, which might be more reliable than our servers for file upload.

Note that I've already changed the backend server file: before, if a file already existed, it would fail with error 400 BAD REQUEST, which would fail the GitHub job too. This made re-trying the job impossible if some (but not all), files were successfully uploaded. Now, if a file already exists, it just does nothing and returns 200 OK.

**Comment by dalboris** [comment]
Looks like explicitly adding `Connection: close` header and/or using the Python `with` block so that it auto-closes the connection after obtaining the response fixes these issues.

Note that according to Python docs `Connection: close` is automatically set when calling `urllib.request.urlopen` : 

> https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen
> urllib.request module uses HTTP/1.1 and includes Connection:close header in its HTTP requests.


But this is probably only true when providing a text URL, not when providing a `Request` object. Indeed, with the `Request` object, we provide headers manually, so I suppose there wasn't the `Connection: close` header.

**Comment by dalboris** [comment]
Closing in favor of: https://github.com/vgc/vgc/issues/659
