### ISSUE TITLE
Throw exceptions for invalid input of dom methods

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#23]
This allows client code to handle invalid input higher-up in the call stack if they wish, and give more incentive not to pass invalid input to functions. Recommended practice is for callers to sanitize input if necessary, and assume that functions do not fail.

**Comment by dalboris** [comment]
Note: here is a concrete example why in the case of `Element::create()`, failing with an exception is better than the current alternative, which is logging the error to the console, then informing the error to the caller by returning nullptr.

Currently, here is an example Python session:

```
>>> from vgc.dom import Document, Element
>>> doc = Document()
>>> e1 = Element(doc, "e1")
>>> e2 = Element(doc, "e2")
Can't create Element: the given parent Document already has a root element
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pybind11::init(): factory function returned nullptr
```

The above doesn't look right: users shouldn't see any confusing pybind11 error. Instead, the following would be less confusing:

```
>>> from vgc.dom import Document, Element
>>> doc = Document()
>>> e1 = Element(doc, "e1")
>>> e2 = Element(doc, "e2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
vgc.dom.HierarchyRequestError: Can't create Element: the given parent Document already has a root element
```

In addition to being more informative, this also allows them to catch and handle these specific errors via traditional Python try/except/finally. Ideally, they should instead fix the python code (it's a logic error not a runtime error), but sometimes this might not be very feasible if somebody else wrote the code, or they may be under a deadline and catching the error would allow them to get the shot done.

Also, note how the common advice of simply using "assert" for logic errors is even worse! Let's suppose that we change the implementation of `Element::create` to the following:

```
Element* Element::create(Document* parent, core::StringId name)
{
    assert(!parent->rootElement() && "Can't create Element: the given parent Document already has a root element");
    return create_(parent, name);
}
```

This crashes the Python console in case users make logic errors:

```
$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vgc.dom import Document, Element
>>> doc = Document()
>>> e1 = Element(doc, "e1")
>>> e2 = Element(doc, "e2")
python3: .../vgc/libs/vgc/dom/element.cpp:47: static vgc::dom::Element* vgc::dom::Element::create(vgc::dom::Document*, vgc::core::StringId): Assertion `!parent->rootElement() && "Can't create Element: the given parent Document already has a root element"' failed.
Aborted (core dumped)
$
```

And if run from the embedded Python console of VGC Illustration, the entire application crashes, here is the log from Qt Creator:

```
Starting .../build-vgc-Desktop_Qt_5_6_2_GCC_64bit-Debug/bin/vgcillustration...
vgcillustration: .../vgc/libs/vgc/dom/element.cpp:47: static vgc::dom::Element* vgc::dom::Element::create(vgc::dom::Document*, vgc::core::StringId): Assertion `!parent->rootElement() && "Can't create Element: the given parent Document already has a root element"' failed.
The program has unexpectedly finished.
The process was ended forcefully.
.../build-vgc-Desktop_Qt_5_6_2_GCC_64bit-Debug/bin/vgcillustration crashed.
```

This is obviously really bad for users. Better handle the exception at a higher level than crash: in the best case we can rollback to an existing valid DOM state, if not possible we might still attempt to save a recovery file, and display a popup saying what error occured, and where the recovery file is. Also, we could automatically send a bug report with a stack trace, so that we can fix the problem in later versions.
