### ISSUE TITLE
AttributeError: module 'plistlib' has no attribute 'Data'

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#444]
I get the following error when deploying on macOS via Travis, see: https://github.com/vgc/vgc/pull/443

```
Creating image /Users/travis/build/vgc/vgc/build/deploy/Release/VGC Illustration Alpha-gh112a 2020-11-02.1.dmg...
Traceback (most recent call last):
  File "/Users/travis/build/vgc/vgc/tools/macos/biplist/__init__.py", line 126, in readPlist
    result = reader.parse()
  File "/Users/travis/build/vgc/vgc/tools/macos/biplist/__init__.py", line 234, in parse
    return self.readRoot()
  File "/Users/travis/build/vgc/vgc/tools/macos/biplist/__init__.py", line 248, in readRoot
    raise NotBinaryPlistException()
biplist.NotBinaryPlistException
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/travis/build/vgc/vgc/tools/macos/biplist/__init__.py", line 141, in readPlist
    result = wrapDataObject(result, for_binary=True)
  File "/Users/travis/build/vgc/vgc/tools/macos/biplist/__init__.py", line 154, in wrapDataObject
    elif isinstance(o, (bytes, plistlib.Data)) and for_binary:
AttributeError: module 'plistlib' has no attribute 'Data'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/travis/build/vgc/vgc/tools/macos/deploy.py", line 1053, in <module>
    dmgbuild.build_dmg(dmgFilename, dmgVolumeName, settings=dmgSettings)
  File "/Users/travis/build/vgc/vgc/tools/macos/dmgbuild/core.py", line 402, in build_dmg
    ret, output = hdiutil('create',
  File "/Users/travis/build/vgc/vgc/tools/macos/dmgbuild/core.py", line 53, in hdiutil
    results = biplist.readPlistFromString(output)
  File "/Users/travis/build/vgc/vgc/tools/macos/biplist/__init__.py", line 191, in readPlistFromString
    return readPlist(io.BytesIO(data))
  File "/Users/travis/build/vgc/vgc/tools/macos/biplist/__init__.py", line 143, in readPlist
    raise InvalidPlistException(e)
biplist.InvalidPlistException: module 'plistlib' has no attribute 'Data'
make[3]: *** [CMakeFiles/deploy] Error 1
make[2]: *** [CMakeFiles/deploy.dir/all] Error 2
make[1]: *** [CMakeFiles/deploy.dir/rule] Error 2
make: *** [deploy] Error 2
```

This seems related to some API of plistlib which has been removed in Python 3.9, which is now the Python version used by Travis CI, see:

https://docs.python.org/3.9/library/plistlib.html

The solution is probably just to update dmgbuild and its dependencies. Looks like this issue is fixed since dmgbuild 1.4.1 and ds_store 1.3.0, see:

https://github.com/al45tair/dmgbuild/issues/24
https://github.com/al45tair/ds_store/issues/7

**Comment by dalboris** [comment]
Updating dmgbuild indeed fixed the problem. Note that I was previously vendoring dmgbuild and its dependencies, but I now rely on pip to install it.
