### ISSUE TITLE
Move Windows builds from AppVeyor to GitHub Actions

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#569]
The last Windows build on AppVeyor failed:

https://ci.appveyor.com/project/vgc/vgc/builds/42433426

Presumably due to the following error: (perhaps there is another issue)

```
Building Custom Rule C:/dev/vgc/CMakeLists.txt
  Downloading https://www.python.org/ftp/python/3.7.5/python-3.7.5-embed-amd64.zip
           to C:\dev\vgc\build\python-3.7.5-embed-amd64.zip
  Traceback (most recent call last):
    File "C:\Python37-x64\lib\urllib\request.py", line 1[317](https://ci.appveyor.com/project/vgc/vgc/builds/42433426#L317), in do_open
      encode_chunked=req.has_header('Transfer-encoding'))
    File "C:\Python37-x64\lib\http\client.py", line 1252, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "C:\Python37-x64\lib\http\client.py", line 1298, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "C:\Python37-x64\lib\http\client.py", line 1247, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "C:\Python37-x64\lib\http\client.py", line 1026, in _send_output
      self.send(msg)
    File "C:\Python37-x64\lib\http\client.py", line 966, in send
      self.connect()
    File "C:\Python37-x64\lib\http\client.py", line 1422, in connect
      server_hostname=server_hostname)
    File "C:\Python37-x64\lib\ssl.py", line 423, in wrap_socket
      session=session
    File "C:\Python37-x64\lib\ssl.py", line 870, in _create
      self.do_handshake()
    File "C:\Python37-x64\lib\ssl.py", line 1139, in do_handshake
      self._sslobj.do_handshake()
  ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "C:/dev/vgc/tools/windows/copy_python.py", line 69, in <module>
      urllib.request.urlretrieve(embedZipUrl, str(embedZipPath))
    File "C:\Python37-x64\lib\urllib\request.py", line 247, in urlretrieve
      with contextlib.closing(urlopen(url, data)) as fp:
    File "C:\Python37-x64\lib\urllib\request.py", line 222, in urlopen
      return opener.open(url, data, timeout)
    File "C:\Python37-x64\lib\urllib\request.py", line 525, in open
      response = self._open(req, data)
    File "C:\Python37-x64\lib\urllib\request.py", line 543, in _open
      '_open', req)
    File "C:\Python37-x64\lib\urllib\request.py", line 503, in _call_chain
      result = func(*args)
    File "C:\Python37-x64\lib\urllib\request.py", line 1360, in https_open
      context=self._context, check_hostname=self._check_hostname)
    File "C:\Python37-x64\lib\urllib\request.py", line 1[319](https://ci.appveyor.com/project/vgc/vgc/builds/42433426#L319), in do_open
      raise URLError(err)
urllib.error.URLError : <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)> [C:\dev\vgc\build\copy_python.vcxproj]
```

Rather than try to fix missing certificate issue on AppVeyor, it's probably a good time to move the Windows builds to GitHub Actions (as we've already done with the macOS and Linux builds)

**Comment by dalboris** [comment]
Windows builds are now successfully ported to GitHub actions. For some reason, *.exe artifacts seem to take an unusually long time to be uploaded to the VGC server, which we may want to investigate later, but at least it works.
